### ISSUE TITLE
Websocket Connection Issue / Coinbase Advanced Trade/ Pure Market Making

### ISSUE THREAD

**Issue by acoronado11-work** [hummingbot/hummingbot#7207]
### Describe the bug

I'm encountering an issue while running the pmm strategy on Hummingbot with the Coinbase Advanced Trade API. The strategy places orders successfully, but Hummingbot fails to recognize that the orders have gone through, leading to further complications when the strategy is stopped. Here are the details:

Issue with Order Tracking and Recognition:
The strategy submits buy and sell limit orders that are successfully placed on the Coinbase Advanced Trade platform.
Despite successful order placement, Hummingbot logs errors indicating failure to submit these orders and fails to track their status accurately.
Errors logged include:
"Error submitting sell LIMIT_MAKER order to Coinbase_advanced_trade for 0.00014 BTC."
"Failed to submit SELL order to Coinbase_advanced_trade. Check API key and network connection."
This leads to the orders not being tracked in the Hummingbot client, and their status remains "Open" even after they are filled or canceled on the exchange.

WebSocket Connection and Order Book Issues:
The order book subscription is initiated correctly, but an error occurs when processing WebSocket messages.
Error messages include:
"Unexpected error occurred when listening to order book streams. Retrying in 5 seconds..."
A TypeError in the json method, "the JSON object must be str, bytes or bytearray, not WebSocketError."
As a result, the strategy does not receive updates on the order book or track client orders accurately.

Due to Hummingbot not recognizing the status of the orders, when the strategy is stopped, the open orders remain on the exchange.
This requires manual intervention to cancel the orders directly on Coinbase, creating inefficiencies and increasing the risk of unintended trades.

![Screenshot (123)](https://github.com/user-attachments/assets/f8df087e-2a97-4ff5-ba71-28aa54f0a223)
![Screenshot (124)](https://github.com/user-attachments/assets/8acb6c94-22c2-4c09-a77d-469e6b170514)

### Steps to reproduce

1. 
2. 
3. 

### Release version

2.0.0

### Type of installation

Docker

**Comment by acoronado11-work** [comment]
@AbdelrahmanHamdy1996 Could this be an issue on Coinbases' side?

**Comment by nikspz** [comment]
hi @AbdelrahmanHamdy1996 @acoronado11-work Could you send a whole log file here?
https://hummingbot.org/client/log-files/

going to crosscheck this issue

**Comment by acoronado11-work** [comment]
@AbdelrahmanHamdy1996  @nikspz 

Any notable findings?

**Comment by acoronado11-work** [comment]
@rapcmia Any ideas on a fix?

**Comment by acoronado11-work** [comment]
> this what i get from coinbase support : Based on the information provided, it seems like your bot is able to place the order, but it's receiving a message that the order failed. This could be due to a number of reasons.
> 
> One possible cause could be that the bot is not correctly interpreting the response from the API. It might be helpful to check the specific error message that the bot is receiving. This could provide more insight into what's going wrong.
> 
> Another possible issue could be related to the number of decimal places specified in the "Price", "Amount", or "Total" fields. If too many decimal places are specified, this could cause the order to fail. In this case, you should reduce the number of decimal places specified in these fields.

What's weird is that it worked previous to last week. My thoughts are that Coinbase updated how their API streams information for the order book in a way that makes it so Hummingbot isn't compatible anymore so I'm in touch with their support to see what exactly was changed on their side. I got upgraded from dev support to engineer support so I expect a response from them either today or tomorrow.

**Comment by nikspz** [comment]
https://github.com/hummingbot/hummingbot/issues/7211

**Comment by luke-tt** [comment]
I am having the same issue with this. 

Returning a KeyError: 'order_id'

Its as if Hummingbot can no longer track the orders that are placed so it doesn't know how to cancel them. This leads to no orders being cancelled and additional orders being placed on the exchange. A possible change in the response object from the Coinbase API?

One other thing to note that has happened for me is when I use the 'stop' command the bot will still continue to place orders until I kill the terminal instance.

**Comment by acoronado11-work** [comment]
Yes I’m getting same issue. I feel like it has to be because of a coinbase API update so I reached out and have been upgraded to engineering support. Waiting on a response but will let you know what they say.



________________________________

**Comment by luke-tt** [comment]
I am not sure what the old response looked like but it this is what it looks like in their docs now 
<img width="490" alt="image" src="https://github.com/user-attachments/assets/c8c7166b-1dc0-4361-8ab5-55cb1fe22af4">

https://docs.cdp.coinbase.com/advanced-trade/reference/retailbrokerageapi_postorder

**Comment by acoronado11-work** [comment]
@luke-tt @AbdelrahmanHamdy1996 

Coinbase engineer support said this

"Could you please confirm the WebSocket read limit on your client? The read limit should be set to greater than 1204.
Buffer size in the WSS.Config -> The read limit should be set to greater than 1204. "

I believe hummingbot default is 1mb but I'm not 100% sure and I'm not sure how to check

**Comment by luke-tt** [comment]
I am not too sure this is the issue.

Looking at my logs the internal order ID generated is the same for each order. I am not sure where this is generated inside hummingbot or taken from. I see its a parameter in the response object from coinbase exchange in the screenshot above so I think this is the cause of the problem. The exchange ID updates which allows us to continue to place orders and cancel them but the client order ID / Internal Order ID doesn't.

**Comment by luke-tt** [comment]
perhaps in the api_params dictionary, possibly it needs to be updated to have a separate client_order_id and order_id now 
<img width="926" alt="image" src="https://github.com/user-attachments/assets/cfc508a8-9136-4530-9e71-a704b108c7af">
![image](https://github.com/user-attachments/assets/410246c7-b38c-42a5-97ad-e6b86a0af73f)

**Comment by nikspz** [comment]
https://github.com/hummingbot/hummingbot/pull/7220

**Comment by luke-tt** [comment]
The above PR will solve the KeyError: 'order_id' but it still wont fix the event listener handler, at least not for me

**Comment by luke-tt** [comment]
i implemented the PR and everything looks to be working as expected now! :D

**Comment by acoronado11-work** [comment]
![Screenshot (136)](https://github.com/user-attachments/assets/1d4e78b8-9229-4858-8cb7-a6b00e899741)


Really? I implemented everything i saw in changed files and still have this issue. Filled the initial order (not sure if it wouldve closed upon stop command) but didn't register in terminal

@luke-tt @isreallee82

**Comment by isreallee82** [comment]
Can I see your log file @acoronado11-work

**Comment by acoronado11-work** [comment]
@isreallee82 
![Screenshot (137)](https://github.com/user-attachments/assets/388ba66b-8ef5-4910-9b52-5212f2dfeb0d)

**Comment by isreallee82** [comment]
i have addressed all this errors @acoronado11-work

**Comment by isreallee82** [comment]
Here https://github.com/hummingbot/hummingbot/pull/7220

**Comment by acoronado11-work** [comment]
@isreallee82 I changed all the same files that were outlined but maybe I made a mistake if @luke-tt was able to fix

**Comment by acoronado11-work** [comment]
@isreallee82 Apologies, I didn't restart the container before trying again. I just did it again and here are the updated logs. Now it won't connect to the order book at all. I made all of the file changes outlined here https://github.com/hummingbot/hummingbot/pull/7220


![Screenshot (139)](https://github.com/user-attachments/assets/bbe9eb9e-45d9-49e5-a4bf-da4634d80b3d)

**Comment by isreallee82** [comment]
this image is showing error for binance

**Comment by acoronado11-work** [comment]
@isreallee82 The top code is JSON error and related to coinbase 

the bottom I meant to grey out because it is irrelevant, as the rates are set to market in use and not binance, sorry I should’ve just scrolled up

**Comment by isreallee82** [comment]
but did you rebuild your container?

**Comment by acoronado11-work** [comment]
@isreallee82 yes the container was rebuilt. Here are full logs for another test

![Screenshot (140)](https://github.com/user-attachments/assets/c682c58c-3534-4df7-9eee-f20a8e2a353f)

**Comment by isreallee82** [comment]
please reconfirm if you incorporate this
 commit https://github.com/hummingbot/hummingbot/pull/7220/commits/dcb318df65af4e163aaf6966260d100dcf1e7d38

**Comment by acoronado11-work** [comment]
Yes I can confirm. changes have been made from both: 
https://github.com/hummingbot/hummingbot/pull/7220
https://github.com/hummingbot/hummingbot/commit/dcb318df65af4e163aaf6966260d100dcf1e7d38

**Comment by acoronado11-work** [comment]
@isreallee82 I can send screenshots of specific code from my system if you would like to confirm.

**Comment by isreallee82** [comment]
2024-JUL-17

Began enforcing portfolio-based filtering for Coinbase Developer Platform (CDP) API keys. This means that CDP API keys are only be able to view Orders and Fills placed on the portfolio that they have been permissioned for.
This also applies to the user channel on the WebSocket API. Users will only receive updates for Orders and Fills placed on the portfolio that their key has been permissioned for.
If you are unable to view Orders and Fills that you expect to see, ensure that your API key has been permissioned for the correct portfolio. If you are unable to view orders placed before 2024-July-16, try querying for them using an API key permissioned for your DEFAULT portfolio.

cc @acoronado11-work

**Comment by acoronado11-work** [comment]
I don’t think this can be the issue as I was running the strategy just fine until the Sept 3 API update from Coinbase



________________________________

**Comment by isreallee82** [comment]
can you set "is_auth_required=False" in line 170 of Coinbase_Advanced_Trade_APIOrder_Book_Data_Source.py @acoronado11-work

**Comment by acoronado11-work** [comment]
@isreallee82 Change made: "is_auth_required=False" in line 170 of coinbase_advanced_trade_api_order_book_data_source.py

Result is no improvement. See logs below

![Screenshot (141)](https://github.com/user-attachments/assets/49619514-c56a-4a7e-95dd-7ef67d67d1ae)

**Comment by isreallee82** [comment]
@acoronado11-work  my coinbase account couldn't be verified due to geo-restriction. which makes it difficult to determine the data coming in. sorry cant help much, error coming from the websocket response itself.

**Comment by isreallee82** [comment]
if its okay we can set up a meeting @acoronado11-work

**Comment by acoronado11-work** [comment]
Yes- please reach out to ***@***.*** and I can invite you to a zoom or discord. I’m available the rest of the afternoon


________________________________

**Comment by isreallee82** [comment]
alright my discord 

leeteelee#8750

**Comment by MementoRC** [comment]
See possible resolution: https://github.com/hummingbot/hummingbot/pull/7220

**Comment by MementoRC** [comment]
> @isreallee82 Change made: "is_auth_required=False" in line 170 of coinbase_advanced_trade_api_order_book_data_source.py

Does this work? Browsing through the doc it seems that they now support non-authenticated websocket, but originally this would have failed.
